Versa/Controllers/CotasVendaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Versa.Domain;
using Versa.Infra.Data.Contexto;
using Versa.Identity.Permissions;

namespace Versa.Controllers
{
    public class CotasVendaController : Controller
    {
        private VersaDbContext db = new VersaDbContext();

        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Index()
        {
            var cotasVenda = db.CotasVenda.Include(c => c.Administradora);
            return View(await cotasVenda.ToListAsync());
        }

        // GET: CotasVenda/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CotasVenda cotasVenda = await db.CotasVenda.FindAsync(id);
            if (cotasVenda == null)
            {
                return HttpNotFound();
            }
            return View(cotasVenda);
        }



        [Authorize(Roles = "Admin")]        
        public ActionResult Create()
        {
            ViewBag.AdministradoraId = new SelectList(db.Administradora, "AdministradoraId", "Descricao");
            return View();
        }

        // POST: CotasVenda/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Credito,Parcela,NumParcela,Valor,Status,Vencimento,TipoCota,AdministradoraId")] CotasVenda cotasVenda)
        {
            if (ModelState.IsValid)
            {
                cotasVenda.Id = Guid.NewGuid();
                db.CotasVenda.Add(cotasVenda);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.AdministradoraId = new SelectList(db.Administradora, "AdministradoraId", "Descricao", cotasVenda.AdministradoraId);
            return View(cotasVenda);
        }

        // GET: CotasVenda/Edit/5
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CotasVenda cotasVenda = await db.CotasVenda.FindAsync(id);
            if (cotasVenda == null)
            {
                return HttpNotFound();
            }
            ViewBag.AdministradoraId = new SelectList(db.Administradora, "AdministradoraId", "Descricao", cotasVenda.AdministradoraId);
            return View(cotasVenda);
        }

        // POST: CotasVenda/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Credito,Parcela,NumParcela,Valor,Status,Vencimento,TipoCota,AdministradoraId")] CotasVenda cotasVenda)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cotasVenda).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.AdministradoraId = new SelectList(db.Administradora, "AdministradoraId", "Descricao", cotasVenda.AdministradoraId);
            return View(cotasVenda);
        }

        // GET: CotasVenda/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CotasVenda cotasVenda = await db.CotasVenda.FindAsync(id);
            if (cotasVenda == null)
            {
                return HttpNotFound();
            }
            return View(cotasVenda);
        }

        // POST: CotasVenda/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            CotasVenda cotasVenda = await db.CotasVenda.FindAsync(id);
            db.CotasVenda.Remove(cotasVenda);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        [AllowAnonymous]
        public ActionResult ListaCotas(TipoCota tipo)
        {
            var cotasVenda = db.CotasVenda.Include(c => c.Administradora);
            var cotas = cotasVenda.Where(c => c.TipoCota == tipo);

           return PartialView("ListaCotas", cotas.ToList());
        }

    }
}

Versa/Views/CotasVenda/Create.cshtml
@using System.Web.Optimization

@model Versa.Domain.CotasVenda

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CotasVenda</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Credito, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Credito, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Credito, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Parcela, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Parcela, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Parcela, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumParcela, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumParcela, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumParcela, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vencimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vencimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vencimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoCota, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.TipoCota, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoCota, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdministradoraId, "AdministradoraId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AdministradoraId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AdministradoraId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Versa/Views/CotasVenda/Delete.cshtml
@model Versa.Domain.CotasVenda

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CotasVenda</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Administradora.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Administradora.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Credito)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Credito)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Parcela)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Parcela)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumParcela)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumParcela)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vencimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vencimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoCota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoCota)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Versa/Views/CotasVenda/Details.cshtml
@model Versa.Domain.CotasVenda

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CotasVenda</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Administradora.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Administradora.Descricao)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Credito)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Credito)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Parcela)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Parcela)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumParcela)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumParcela)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Valor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Valor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Vencimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Vencimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TipoCota)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TipoCota)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Versa/Views/CotasVenda/Edit.cshtml
@using System.Web.Optimization

@model Versa.Domain.CotasVenda

@{
                /**/

                ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>CotasVenda</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Credito, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Credito, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Credito, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Parcela, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Parcela, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Parcela, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumParcela, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumParcela, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumParcela, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Valor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Valor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Valor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Status)
                    @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Vencimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Vencimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Vencimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TipoCota, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.TipoCota, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TipoCota, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdministradoraId, "AdministradoraId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("AdministradoraId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.AdministradoraId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Versa/Views/CotasVenda/Index.cshtml
@model IEnumerable<Versa.Domain.CotasVenda>
@using Versa.Domain
@{
    ViewBag.Title = "Index";
}

<style>
    .myButton {
        -webkit-border-radius: 18px;
        -moz-border-radius: 18px;
        border-radius: 18px;
        -webkit-box-shadow: 0px 1px 3px #000000;
        -moz-box-shadow: 0px 1px 3px #000000;
        box-shadow: 0px 1px 3px #000000;
        color: inherit;
        color: white !important;
        background: #2F5362;
        padding: 5px 20px 5px 20px;
        text-decoration: none;
    }

        .myButton:hover {
            background: #ffffff;
            color: black !important;
            text-decoration: none;
        }

    .alinha_a_direita {
        text-align: right;
    }
    .alinha_ao_centro {
        text-align: center;
    }
</style>
<div class="theme-page padding-bottom-70">
    <div class="row gray full-width page-header vertical-align-table">
        <div class="row full-width padding-top-bottom-50 vertical-align-cell">
            <div class="row">
                <div class="page-header-left">
                    <h1>COTAS A VENDA</h1>
                </div>
                <div class="page-header-right">
                    <div class="bread-crumb-container">
                        <label>Você está aqui:</label>
                        <ul class="bread-crumb">
                            <li>
                                <a href="@Url.Action("Index", "Home")" title="Página Principal">
                                    HOME
                                </a>
                            </li>
                            <li class="separator">
                                &#47;
                            </li>
                            <li>
                                COTAS A VENDA
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <p>
        @{
            if (User.Identity.IsAuthenticated)
            {
                @Html.ActionLink("Adicionar", "Create", "CotasVenda", null, new { @class = "btn btn-success" })
                <h4>@HttpContext.Current.User.Identity.Name</h4>
            }
        }
    </p>
    <div class="col-md-10 col-md-offset-1">
        <h3 class="box-header">COTAS A VENDA AUTOM&Oacute;VEIS</h3>
        @{Html.RenderAction("ListaCotas", "CotasVenda", new { tipo = TipoCota.Automoveis });}

        </br>
        <h3 class="box-header">COTAS A VENDA AUTOM&Oacute;VEIS</h3>
        @{Html.RenderAction("ListaCotas", "CotasVenda", new { tipo = TipoCota.Imoveis });}

    </div>
</div>

Versa/Views/CotasVenda/ListaCotas.cshtml
@model IEnumerable<Versa.Domain.CotasVenda>
<div class="table-responsive">
    <table class="table table-condensed table-bordered table-hover">
        <tr>
            <th class="alinha_a_direita">
                @Html.DisplayNameFor(model => model.Credito)
            </th>
            <th class="alinha_a_direita">
                @Html.DisplayNameFor(model => model.Parcela)
            </th>
            <th class="alinha_ao_centro">
                @Html.DisplayNameFor(model => model.NumParcela)
            </th>
            <th class="alinha_a_direita">
                @Html.DisplayNameFor(model => model.Valor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Administradora.Descricao)
            </th>

            <th class="alinha_ao_centro">
                @Html.DisplayNameFor(model => model.Vencimento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TipoCota)
            </th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td class="alinha_a_direita">
                    @Html.DisplayFor(modelItem => item.Credito)
                </td>
                <td class="alinha_a_direita">
                    @Html.DisplayFor(modelItem => item.Parcela)
                </td>
                <td class="alinha_ao_centro">
                    @Html.DisplayFor(modelItem => item.NumParcela)
                </td>
                <td class="alinha_a_direita">
                    @Html.DisplayFor(modelItem => item.Valor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Administradora.Descricao)
                </td>
                <td class="alinha_ao_centro">
                    @Html.DisplayFor(modelItem => item.Vencimento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TipoCota)
                </td>
                <td>
                    @{
                        if (!User.Identity.IsAuthenticated)
                        {
                            @Html.ActionLink("Comprar", "Details", null, new { id = item.Id }, new { @class = "btn btn-sm myButton" })
                        }
                        else
                        {
                            @Html.ActionLink("Editar", "Edit", null, new { id = item.Id }, new { @class = "btn  btn-info" })
                            @Html.ActionLink("Excluir", "Delete", null, new { id = item.Id }, new { @class = "btn btn-danger" })

                        }
                    }
                </td>
            </tr>
        }

    </table>
</div>