Versa/Controllers/QuemSomosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Versa.Controllers
{
    public class QuemSomosController : Controller
    {
        // GET: QuemSomos
        public ActionResult Index()
        {
            return View();
        }
    }
}

Versa/Controllers/VendaSuaCotaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Versa.Controllers
{
    public class VendaSuaCotaController : Controller
    {
        // GET: VendaSuaCota
        public ActionResult Index()
        {
            return View();
        }
    }
}

Versa/Views/Shared/NotFound.cshtml
@using System
@{
    // 404 Not Found
    //
    // This view was added by NotFoundMVC
    // For inspiration see: https://www.google.be/search?q=example+404+page
    //
    // The following properties are available in the ViewBag:
    // ViewData["RequestedUrl"]
    // ViewData["ReferrerUrl"]
    //

    ViewBag.Title = "Página não encontrada!";
}

<div>
    <a href="/Home/Index" target="_self">
        <img src="~/images/404.png" alt="Página não encontrada!" />
    </a>
</div>
<br /><hr /><br />
<div class="alert alert-danger">

    <p>Url que você tentou acessar: @ViewBag.RequestedUrl</p>
    @if (ViewData["ReferrerUrl"] != null)
    {
        <p>Go back to the <a href="@ViewData["ReferrerUrl"]">previous page</a>.</p>
    }
</div>


<script type="text/javascript">
    var GOOG_FIXURL_LANG = '@System.Globalization.CultureInfo.CurrentCulture.Name.Substring(0,2)';
    var GOOG_FIXURL_SITE = '@Request.Url.GetLeftPart(UriPartial.Authority)'
</script>
<script type="text/javascript" src="//linkhelp.clients.google.com/tbproxy/lh/wm/fixurl.js"></script>

@* Error page must be longer than 512 bytes for IE and Chrome to show it. So add padding in case we're short. *@
@(new string(' ', 512))

Versa/Views/Shared/_Layout.cshtml
@using System.Web.Optimization

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <title>
        Versa Cons&oacute;rcio
    </title>
    <!--meta-->
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.2" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="keywords" content="Construction, Renovation" />
    <meta name="description" content="Responsive Construction Renovation Template" />
    <!--slider revolution-->
    <!--style-->
    @*<link href='//fonts.googleapis.com/css?family=Lora:100,300,400,500,600,700,900' rel='stylesheet' type='text/css'>*@
    @*<link href='//fonts.googleapis.com/css?family=Lora' rel='stylesheet' type='text/css'>*@
    <link rel="stylesheet" id="google-font-primary-css" href="//fonts.googleapis.com/css?family=Lora%3Aregular&amp;subset=latin&amp;ver=4.9.9" type="text/css" media="all">


    @Scripts.Render("~/bundles/modernizr")

    @Styles.Render("~/Content/bootstrap")
    @Styles.Render("~/Content/css")

    <link rel="shortcut icon" href="images/favicon.ico">

</head>
<body>
    <script type="text/javascript">
        var stm_sticky = '';
    </script>

    <div class="site-container">
        @*Cabecalho*@
        <div class="stm-header stm-header__hb" id="stm_medical">
            <div class="stm-header__row_color stm-header__row_color_top elements_in_row_3">
                <div class="container">
                    <div class="stm-header__row stm-header__row_top">
                        <div class="stm-header__cell stm-header__cell_left">
                            <div class="stm-header__element object2942 stm-header__element_">
                                <div class="stm-text fwn">
                                    &nbsp;
                                </div>
                            </div>
                        </div>
                        <div class="stm-header__cell stm-header__cell_center">
                            <div class="stm-header__element object2944 stm-header__element_">
                                <div class="stm-text fwn">
                                    &nbsp;
                                </div>
                            </div>
                        </div>
                        <div class="stm-header__cell stm-header__cell_right">
                            <div class="stm-header__element object2948 stm-header__element_">
                                <div class="stm-text fwn">
                                    &nbsp;
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="stm-header__row_color stm-header__row_color_center elements_in_row_1">
                <div class="container">
                    <div class="stm-header__row stm-header__row_center">
                        <div class="stm-header__cell stm-header__cell_right">
                            <div class="stm-header__element object2866 stm-header__element_default">
                                <div class="stm-navigation heading_font stm-navigation__default stm-navigation__default stm-navigation__none stm-navigation__">
                                    <ul>
                                        <li id="menu-item-1024" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-home current-menu-item page_item page-item-924 current_page_item menu-item-1024">
                                            @Html.ActionLink("Home", "Index", "Home")
                                        </li>
                                        <li id="menu-item-1167" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1167">
                                            @Html.ActionLink("Venda sua cota", "Index", "VendaSuaCota")
                                        </li>
                                        <li id="menu-item-1296" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1296">
                                            <a href="/CotasVenda/Index">Cotas &agrave; Venda</a>
                                        </li>
                                        <li id="menu-item-1023" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-1023">
                                            @Html.ActionLink("Quem Somos", "Index", "QuemSomos")
                                        </li>

                                        <li id="menu-item-959" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-959">
                                            <a href="http://versaconsorcios.com.br/contact-style-1/">Contato</a>
                                        </li>

                                        @Html.Partial("_LoginPartial")

                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="stm-header__row_color stm-header__row_color_bottom elements_in_row_2">
                <div class="container">
                    <div class="stm-header__row stm-header__row_bottom">
                        <div class="stm-header__cell stm-header__cell_left">
                            <div class="stm-header__element object2937 stm-header__element_">
                                <div class="stm-text fwn">
                                    &nbsp;
                                </div>
                            </div>
                            <div class="stm-header__element object3561 stm-header__element_">
                                <div class="stm-logo">
                                    <a href="@Url.Action("Index", "Home")" title="Versa Consorcios">
                                        <img width="176" height="71" src="@Url.Content("~/images/LogoVersa.png")" , alt="Versa Consórcios" class="attachment-full size-full" style="width:196px" />
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="stm-header__cell stm-header__cell_right">
                            <div class="stm-header__element object3530 stm-header__element_">
                                <div class="stm-iconbox">
                                    <i class="stm-iconbox__icon stm_hb_mtc stm-iconbox__icon_left icon_22px fa fa-phone-square"></i>
                                    <div class="stm-iconbox__info">
                                        <div class="stm-iconbox__text stm-iconbox__text_nomargin">
                                            Fale Conosco
                                        </div>
                                        <div class="stm-iconbox__description">
                                            (11) 3881-4010&nbsp; (11) 9.8919-0560
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="stm-header__element object761 stm-header__element_">
                                <div class="stm-iconbox">
                                    <i class="stm-iconbox__icon stm_hb_mtc stm-iconbox__icon_left icon_22px fa fa-whatsapp"></i>
                                    <div class="stm-iconbox__info">
                                        <div class="stm-iconbox__text stm-iconbox__text_nomargin">
                                            WhatsApp
                                        </div>
                                        <div class="stm-iconbox__description">
                                            (11) 9.8919-0560
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        <div class="stm-header__overlay">
        </div>

        <div class="stm_mobile__header">
            <div class="container">
                <div class="stm_flex stm_flex_center stm_flex_last stm_flex_nowrap">
                    <div class="stm_mobile__switcher stm_flex_last js_trigger__click" data-element=".stm-header, .stm-header__overlay" data-toggle="false">
                        <span class="stm_hb_mbc">
                        </span>
                        <span class="stm_hb_mbc">
                        </span>
                        <span class="stm_hb_mbc">
                        </span>
                    </div>
                </div>
            </div>
        </div>

        @*Fim Cabecalho*@


        @RenderBody()

        <div class="row yellow full-width padding-top-bottom-30">
            <div class="row">
                <div class="column column-1-3">
                    <ul class="contact-details-list">
                        <li class="sl-small-phone">
                            <p>
                                <br>Telefones
                                <br>
                                <br>Telefone&nbsp;&nbsp;&nbsp;&nbsp;(11) 3881-4010
                                <br>Celular&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(11) 9.8919-0560
                                <br>WhatsApp	(11) 9.8919-0560
                            </p>
                        </li>
                    </ul>
                </div>
                <div class="column column-1-3">
                    <ul class="contact-details-list">
                        <li class="sl-small-location">
                            <p>
                                <br>Nosso Endere&ccedil;o
                                <br>
                                <br>Rua Dr. Luiz Migliano, 1986
                                <br>S&atilde;o Paulo - SP - 05711-001
                                <br>
                            </p>
                        </li>
                    </ul>
                </div>
                <div class="column column-1-3">
                    <ul class="contact-details-list">
                        <li class="sl-small-mail">
                            <p>
                                <br>E-mail
                                <br>
                                <br>contato@versaconsorcios.com.br
                                <br>
                            </p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="row align-center padding-top-bottom-30">
            <span class="copyright">
                &copy; Copyright 2018
                <a target="_blank" title="Versa Cons&oacute;rcios" href="www.versaconsorioc.com.br">Versa Cons&oacute;rcios</a> by
                <a target="_blank" title="MidiaOne" href="http://www.midiaone.com.br">MidiaOne</a>
            </span>
        </div>
    </div>
    <a href="#top" class="scroll-top animated-element template-arrow-up" title="Scroll to top"></a>
    <!--js-->


    @Scripts.Render("~/bundles/js")
    @Scripts.Render("~/bundles/bootstrap")




    @RenderSection("styles", required: false)
    @RenderSection("scripts", required: false)
</body>
</html>

Versa/Views/Shared/_LayoutFooter.cshtml
    <!-- / #wrapper -->
<div id="footer" class="clearfix sidebar-page right-sidebar-page">
    <!-- Start #footer  -->
    <p class="pull-left">
        Copyrights &copy; @DateTime.Now.Year.ToString() <a href="http://cooperchip.com.br/" class="color-blue strong" target="_blank">Cooperchip Informática</a>. Todos os direitos reservados.
    </p>
    <p class="pull-right">
        <a href="#" class="mr5">Termos de uso</a>
        |
        <a href="#" class="ml5 mr25">Política de Privacidade</a>
    </p>
</div>
<!-- / #wrapper -->
<!-- End #footer  -->

Versa/Views/Shared/_LayoutPage1.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" id="google-font-primary-css" href="//fonts.googleapis.com/css?family=Lora%3Aregular&amp;subset=latin&amp;ver=4.9.9" type="text/css" media="all">
    <link href="~/Content/Teste1.css" rel="stylesheet" />

</head>
<body>


    <!--======== header =========-->
    <header id="home">
        @*<div class="small-menu small-menu-2">
                <div class="container">
                    <div class="row">
                            <div class="col-md-7 col-sm-8 col-xs-5">
                                <ul class="list-inline info-link">
                                    <li title="Language">
                                        <i class="fa fa-globe"></i>
                                        <span class="hidden-xs">
                                            Language : English
                                        </span>
                                    </li>
                                    <li title="Hot Line">
                                        <i class="fa fa-phone"></i>
                                        <span class="hidden-xs">
                                            (+123) 45678910
                                        </span>
                                    </li>
                                    <li title="Show Time">
                                        <i class="fa fa-clock-o"></i>
                                        <span class="hidden-xs">
                                            Sat - Wet : 9.00 - 18.00
                                        </span>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md-5 col-sm-4 col-xs-7">
                                <ul class="list-inline pull-right social-link">
                                    <li title="Email">
                                        <i class="fa fa-paper-plane"></i>
                                        <span class="hidden-sm hidden-xs">
                                            info@bootultra.com
                                        </span>
                                    </li>
                                    <li title="Facebook">
                                        <i class="fa fa-facebook"></i>
                                    </li>
                                    <li title="Google+">
                                        <i class="fa fa-google-plus"></i>
                                    </li>
                                    <li title="Twitter">
                                        <i class="fa fa-twitter"></i>
                                    </li>
                                    <li title="Dribbble">
                                        <i class="fa fa-dribbble"></i>
                                    </li>
                                </ul>
                            </div>
                        </div>
                </div>
            </div>*@
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <!-- menu 4 -->
                <div class="navbar navbar-default default-menu menu-4" role="navigation">
                    <div class="container">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu-4" aria-expanded="false">
                                <span class="sr-only">
                                    Toggle navigation
                                </span>
                                <span class="icon-bar">
                                </span>
                                <span class="icon-bar">
                                </span>
                                <span class="icon-bar">
                                </span>
                            </button>
                            <a class="navbar-brand default-logo" href="#"> <img src="~/images/LogoVersa.png" class="img-responsive"></a>
                        </div>
                        <div class="collapse navbar-collapse" id="menu-4">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="active">
                                    <a class="scroll" href="#home">Home</a>
                                </li>
                                <li>
                                    <a class="scroll" href="#about-us">Venda Sua Cota</a>
                                </li>
                                <li>
                                    <a class="scroll" href="#service">Cotas a Venda</a>
                                </li>
                                <li>
                                    <a class="scroll" href="#team">Quem Somos</a>
                                </li>
                                <li>
                                    <a class="scroll" href="#contact">Contato</a>
                                </li>
                                @*<li>
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                            <i class="fa fa-shopping-cart">
                                                <span class="cart-number">
                                                    1
                                                </span>
                                            </i>
                                        </a>
                                        <ul class="dropdown-menu cart">
                                            <li>
                                                <img src="images/cart1.jpg" alt="" />
                                                <i class="fa fa-trash-o pull-right"></i>                                                <strong>Women / Clothe</strong>                                                <small>Bright Desses in Leaf</small>
                                                <span>
                                                    2 X 400
                                                </span>
                                            </li>
                                            <li>
                                                <p>
                                                    <i class="fa fa-trash-o"></i> Empty Carts
                                                    <span class="pull-right">
                                                        SubTotal :
                                                        <span>
                                                            <span class="color">
                                                                $1200
                                                            </span>
                                                        </span>
                                                    </span>
                                                </p>
                                            </li>
                                            <li class="text-center">
                                                <p>
                                                    <a class="btn btn-default" href="#">View Cart</a>
                                                    <a class="btn btn-default" href="#">Checkout</a>
                                                </p>
                                            </li>
                                        </ul>
                                    </li>*@
                                @*<li>
                                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                            <i class="fa fa-search"></i>
                                        </a>
                                        <ul class="dropdown-menu list-search">
                                            <li>
                                                <form class="navbar-form navbar-left nav-search" role="search">
                                                    <div class="form-group">
                                                        <input type="text" class="form-control" placeholder="Search">
                                                        <i class="fa fa-search"></i>
                                                    </div>
                                                </form>
                                            </li>
                                        </ul>
                                    </li>*@
                            </ul>
                        </div>
                        <div class="row">
                            <div class="col-md-11 col-sm-12 col-xs-10">
                                <ul class="list-inline info-link">
                                    <li title="Hot Line">
                                        <i class="fa fa-phone"></i>
                                        <span class="hidden-xs">
                                            (+123) 45678910
                                        </span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <!-- end menu -->
                </div>
            </div>
        </div>
    </header>
    <!--======== end header =========-->




    <div>
        @RenderBody()
    </div>
    <script src="~/js/jquery-1.11.3.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>