Versa/Controllers/AdministradoraController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Versa.Domain;
using Versa.Infra.Data.Contexto;

namespace Versa.Controllers
{
    public class AdministradoraController : Controller
    {
        private VersaDbContext db = new VersaDbContext();

        // GET: Administradora
        public async Task<ActionResult> Index()
        {
            return View(await db.Administradora.ToListAsync());
        }

        // GET: Administradora/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Administradora administradora = await db.Administradora.FindAsync(id);
            if (administradora == null)
            {
                return HttpNotFound();
            }
            return View(administradora);
        }

        // GET: Administradora/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Administradora/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "AdministradoraId,Descricao")] Administradora administradora)
        {
            if (ModelState.IsValid)
            {
                db.Administradora.Add(administradora);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(administradora);
        }

        // GET: Administradora/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Administradora administradora = await db.Administradora.FindAsync(id);
            if (administradora == null)
            {
                return HttpNotFound();
            }
            return View(administradora);
        }

        // POST: Administradora/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "AdministradoraId,Descricao")] Administradora administradora)
        {
            if (ModelState.IsValid)
            {
                db.Entry(administradora).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(administradora);
        }

        // GET: Administradora/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Administradora administradora = await db.Administradora.FindAsync(id);
            if (administradora == null)
            {
                return HttpNotFound();
            }
            return View(administradora);
        }

        // POST: Administradora/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Administradora administradora = await db.Administradora.FindAsync(id);
            db.Administradora.Remove(administradora);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Versa/Views/Administradora/Create.cshtml
@using System.Web.Optimization

@model Versa.Domain.Administradora

@{
    ViewBag.Title = "Nova Administradora";
}

<h2>Nova Administradora</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-4">
                <input type="submit" value="Adicionar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar à Lista", "Index", "Administradora", null, new { @class="btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Versa/Views/Administradora/Delete.cshtml
@model Versa.Domain.Administradora

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Administradora</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Versa/Views/Administradora/Details.cshtml
@model Versa.Domain.Administradora

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Administradora</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descricao)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.AdministradoraId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Versa/Views/Administradora/Edit.cshtml
@using System.Web.Optimization

@model Versa.Domain.Administradora

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Administradora</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AdministradoraId)

        <div class="form-group">
            @Html.LabelFor(model => model.Descricao, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-4">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Versa/Views/Administradora/Index.cshtml
@model IEnumerable<Versa.Domain.Administradora>

@{
    ViewBag.Title = "Lista de Administradora";
}

<h3>Lista de Administradora</h3>

<p>
    @Html.ActionLink("Adicionar", "Create", "Administradora", null, new { @class="btn btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Descricao)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Descricao)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", null, new { id = item.AdministradoraId }, new { @class = "btn btn-info" })
            @Html.ActionLink("Detalhes", "Details", null, new { id = item.AdministradoraId }, new { @class = "btn btn-default" })
            @Html.ActionLink("Excluir", "Delete", null, new { id = item.AdministradoraId }, new { @class = "btn btn-danger" })
        </td>
    </tr>
}

</table>